{{- if ne .Release.Namespace "beta" }}
{{- range $i, $job := .Values.cronJobs -}}
{{- if $i -}}
---
{{ end -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Values.name }}-{{ .name }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          imagePullSecrets:
          - name: asia-gcr-io
          containers:
          - name: {{ .name }}
            image: {{ if .image }}{{ .image }}{{ else }}{{ $.Values.image.repository }}:{{ $.Values.image.tag }}{{ end }}
            env:
            - name: MAINTAINER
              value: be.xyz
            {{- if eq (kindOf $.Values.env) "slice" }}
{{ toYaml $.Values.env | indent 12 }}
            {{- else }}
            {{- range $key, $val := $.Values.env }}
            - name: {{ $key -}}
            {{- if eq (kindOf $val) "map" }}
{{ $val | toYaml | indent 14 -}}
            {{- else }}
              value: {{ $val | quote }}
            {{- end -}}
            {{- end }}
            {{- end }}
            resources:
{{ toYaml $.Values.resources | indent 14 }}
{{- if .command }}
            command:
{{ toYaml .command | indent 12 -}}
{{- end -}}
{{- if .args -}}
            args:
{{ toYaml .args | indent 12 -}}
{{- end }}
          restartPolicy: OnFailure
{{ end }}
{{- end }}
