{{ if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{ if .Values.service.containerGrpcPort }}
    - port: {{ .Values.service.containerGrpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpclb
  {{end}}
  selector:
    app: {{ include "app.name" . }}
{{ end }}
